---
title: "NY_NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(dplyr)
```

```{r}
library(p8105.datasets)
data("ny_noaa")
```

```{r}
ny_noaa = ny_noaa %>% 
  janitor::clean_names() %>% 
  drop_na(prcp) %>% 
  drop_na(snow) %>% 
  drop_na(snwd) %>% 
  drop_na(tmax) %>% 
  drop_na(tmin)  %>% 
  filter(prcp != 0 & snow != 0 & snwd != 0) %>% 
  # Unify the unit
  mutate(
    prcp = prcp/10,
    # change the unit of precipitation from tenths of mm to mm for later calculation
    tmax = as.numeric(tmax)/10,
    tmin = as.numeric(tmin)/10
    # change the unit of minimum and maximum temperature from tenths of degrees C to degrees C for later calculation
  ) %>%  #Separate date into year, month, day
  separate(date,into = c("year","month","day"),sep = "-") %>% 
  mutate(
     month = recode(month, "01" = "January",
                  "02" = "February",
                  "03" = "March",
                  "04" = "April",
                  "05" = "May",
                  "06" = "June",
                  "07" = "July",
                  "08" = "Augest",
                  "09" = "September",
                  "10" = "October",
                  "11" = "November", 
                  "12" = "December"
                  )
     )
```

